"""empty message

Revision ID: a8b7016482cb
Revises: c87cb00c16e4
Create Date: 2016-08-02 16:37:50.599430

"""

# revision identifiers, used by Alembic.
revision = 'a8b7016482cb'
down_revision = 'c87cb00c16e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('farmers_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'farmers_name')
    ### end Alembic commands ###
