"""empty message

Revision ID: bf4b443fb548
Revises: d21363458953
Create Date: 2016-07-12 08:37:10.698829

"""

# revision identifiers, used by Alembic.
revision = 'bf4b443fb548'
down_revision = 'd21363458953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_to', sa.String(length=64), nullable=True),
    sa.Column('message_body', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_message_body'), 'messages', ['message_body'], unique=True)
    op.create_index(op.f('ix_messages_send_to'), 'messages', ['send_to'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_send_to'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_body'), table_name='messages')
    op.drop_table('messages')
    ### end Alembic commands ###
