"""empty message

Revision ID: caaf448a20a9
Revises: 77f929c5622b
Create Date: 2016-08-01 11:06:31.805927

"""

# revision identifiers, used by Alembic.
revision = 'caaf448a20a9'
down_revision = '77f929c5622b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
